dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
      - libspdlog-dev
script:
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip-cleanup: true
  script:
    - curl -f -T template-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uredfoer:$BINTRAY_API_KEY "https://api.bintray.com/content/redfoer/template/template_test/$TRAVIS_BUILD_NUMBER/template-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"